#!/usr/bin/env python3
"""
Determine which record to prioritize for duplicate strain names.
Outputs a text file with a single record id per line.
"""
import argparse
from csv import DictReader
from enum import Enum
from sys import stdin
from typing import Iterable
from augur.io.json import load_ndjson
from augur.io.print import print_err


class Prioritization(Enum):
    """
    Order of prioritization:
    1. Strain id is included in the TSV providied via `--prioritized-ids`
    2. If all else equal, first record wins.
    """
    HARDCODED = "hardcoded"
    FIRST_RECORD = "first record"


def load_prioritized_ids(prioritized_ids_file: str) -> dict:
    """
    Parse *prioritized_ids_file* to return a dict with the
    `strain` as the key and `id` as the value.

    Raises an Exception if there are duplicate strains in the file.
    """
    prioritized_ids = {}
    with open(prioritized_ids_file, "r", newline="") as fh:
        reader = DictReader(fh, delimiter="\t")
        for row in reader:
            strain = row["strain"]
            record_id = row["id"]

            if strain in prioritized_ids:
                raise Exception(f"Found duplicate strain {strain!r} in {prioritized_ids_file!r}.")

            prioritized_ids[strain] = record_id

    return prioritized_ids


def track_ids_per_strain(records: Iterable[dict],
                         strain_field: str,
                         id_field: str,
                         hardcoded_ids: dict) -> dict[str, dict[str, set[Prioritization]]]:
    """
    Iterate over *records* to track ids per strain.
    Includes Prioritization reason for each id.
    """
    ids_per_strain: dict = {}

    for record in records:
        strain = record.get(strain_field)
        record_id = record.get(id_field)

        if strain is None:
            raise Exception(f"Records must have the expected strain field {strain_field!r}")

        if record_id is None:
            raise Exception(f"Records must have the expected id field {id_field!r}")

        if strain not in ids_per_strain:
            ids_per_strain[strain] = {record_id: {Prioritization.FIRST_RECORD}}

        if hardcoded_id := hardcoded_ids.get(strain):
            if hardcoded_id == record_id:
                ids_per_strain[strain][record_id].add(Prioritization.HARDCODED)

    return ids_per_strain

def pick_id_per_strain(
        ids_per_strain: dict[str, dict[str, set[Prioritization]]]) -> list:
    """
    For each strain in *ids_per_strain*, pick a single id to include in
    the output.
    """
    ids_to_output = []

    for strain, ids in ids_per_strain.items():
        for id, reasons in ids.items():
            if Prioritization.HARDCODED in reasons:
                ids_to_output.append(id)
                break

            
    return ids_to_output


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)

    parser.add_argument("--strain-field", default="strain",
        help="The record field containing the strain name.")
    parser.add_argument("--id-field", default="gisaid_epi_isl",
        help="The record field containing a record id. " + \
             "If providing the `--prioritized-ids` file, then this id field " + \
             "will be used to match the prioritized ids. " + \
             "Also included in the warning logs for records with duplicate strains.")
    parser.add_argument("--prioritized-ids",
        help="An optional TSV file with prioritized ids for specific strains. " + \
             "The file is expected to have the columns `strain` and `id` " + \
             "and the `strain` column is expected to have unique strains. " + \
             "Any records with a strain that is included in this file " + \
             "will be dropped if the record id does not match the prioritized id. ")
    parser.add_argument("--output", required=True,
        help="Output of prioritized ids per strain.")

    args = parser.parse_args()

    hardcoded_prioritized_ids = {}
    if args.prioritized_ids:
        hardcoded_prioritized_ids = load_prioritized_ids(args.prioritized_ids)

    records = load_ndjson(stdin)
    ids_per_strain = track_ids_per_strain(
        records,
        args.strain_field,
        args.id_field,
        hardcoded_prioritized_ids)

    prioritized_ids = prioritize_id_per_strain(ids_per_strain)
